#! /bin/bash

# NOTE: At the moment, this has only been confirmed to work with PHP 7

PHP_WORKSPACE_CONTAINER=$(docker-compose ps | grep laradock_workspace | cut -d" " -f 1)

WINPTY=""
if [[ $(expr substr $(uname -s) 1 5) == "MINGW" ]]; then
    WINPTY="winpty"
fi

xdebug_status ()
{
    echo 'xDebug status'
    $WINPTY docker exec -it $PHP_WORKSPACE_CONTAINER bash -c 'php -v'
}

xdebug_start ()
{
    echo 'Start xDebug'
    $WINPTY docker exec -it $PHP_WORKSPACE_CONTAINER bash -c "sed -i 's/^;zend_extension=/zend_extension=/g' /etc/php/7.0/cli/conf.d/20-xdebug.ini"
    $WINPTY docker exec --user=laradock -it $PHP_WORKSPACE_CONTAINER bash -c 'cat ~/.bash_aliases | grep -v "^export PHP_IDE_CONFIG=" > ~/.bash_aliases'
    if [[ $1 != "" ]]; then
        $WINPTY docker exec --user=laradock -it $PHP_WORKSPACE_CONTAINER bash -c "echo export PHP_IDE_CONFIG=\\\"serverName=$1\\\" >> ~/.bash_aliases"
    fi
    $WINPTY docker exec --user=laradock -it $PHP_WORKSPACE_CONTAINER bash -c 'php -v'
    #; echo PHP_IDE_CONFIG: "$PHP_IDE_CONFIG";
}

xdebug_stop ()
{
    echo 'Stop xDebug'
    $WINPTY docker exec -it $PHP_WORKSPACE_CONTAINER bash -c "sed -i 's/^zend_extension=/;zend_extension=/g' /etc/php/7.0/cli/conf.d/20-xdebug.ini"
    $WINPTY docker exec --user=laradock -it $PHP_WORKSPACE_CONTAINER bash -c 'cat ~/.bash_aliases | grep -v "^export PHP_IDE_CONFIG=" > ~/.bash_aliases'
    $WINPTY docker exec --user=laradock -it $PHP_WORKSPACE_CONTAINER bash -c 'php -v'
}

case $1 in
    stop|STOP)
        xdebug_stop
        ;;
    start|START)
        xdebug_start $2
        ;;
    status|STATUS)
        xdebug_status
        ;;
    *)

    echo "xDebug [Stop | Start | Status] in the ${PHP_WORKSPACE_CONTAINER} container."
    echo "xDebug must have already been installed."
    echo "Usage:"
    echo "  ./xdebugPhpFpm stop|start serverName|status"
    echo "stop for current session: export PHP_IDE_CONFIG="
esac

exit 1
